version: '3.0'

services:      
  web:
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    volumes: 
      - registry:/root/.cargo/registry
volumes:
  registry:
    driver: local